### ISSUE TITLE
Vaadin 24 compatibility?

### ISSUE THREAD

**Issue by flozano** [vaadin-component-factory/lookup-field-flow#21]
I am having problems after minor upgrade of vaadin 24.x and it seems I'm not the only one as per the forums (https://vaadin.com/forum/t/failed-to-execute-define-on-customelementregistry-the-name-vaadin-overlay-has-already-been-used-with-this-registry/166535/4). Is this component really compatible?

**Comment by flozano** [comment]
Reverting from 24.4.4 to 24.3.5 works again

**Comment by jcgueriaud1** [comment]
The demo in the source code is using Vaadin 24.3.2 and it's working.
I'll update the demo to 24.4.6 and check if there is an issue

**Comment by jcgueriaud1** [comment]
From what I see I have the Vaadin overlay version 24.4.2 and 24.4.3. I'm checking why I have this issue.

**Comment by jcgueriaud1** [comment]
There is a new version 24.0.4: https://vaadin.com/directory/component/lookup-field

Can you try it and check if it solves the issue?

**Comment by flozano** [comment]
It seems to work! I will try more deeply later, but so far so good.

**Comment by flozano** [comment]
out of curiosity, how does the fix look like? I guess the git repo is not yet updated

**Comment by flozano** [comment]
Actually in dev mode it doesn't work, same happens :/

**Comment by jcgueriaud1** [comment]
The repo has been updated.

The fix is in the web component:
https://github.com/vaadin-component-factory/vcf-lookup-field/commit/e1d55504c742f3b1b47f133384ea6799d913d9a0#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L48

The previous version of the webcomponent was using the version ^23.3.6, updated automatically by Vaadin to 24.x.x (the version of the framework) but it was broken for 24.4.x because the version 24.4.3 was used instead of 24.4.2.

The package dependency in npm is not easy :/

**Comment by jcgueriaud1** [comment]
> Actually in dev mode it doesn't work, same happens :/

What do you mean by dev mode?
I've tested with vaadin.frontend.hotdeploy=true and false and both are working.

**Comment by flozano** [comment]
I was trying without vaadin development mode and it worked, but now with development mode same happens. I'm not vaadin expert at all, so let me try to find out more and report this issue properly before bothering you further.

**Comment by flozano** [comment]
Feel free to close, there's another component in my code with the same issue as this one had.
